### ISSUE TITLE
Vagrant Instructions Failing

### ISSUE THREAD

**Issue by codeaudit** [hopshadoop/hops-hadoop-chef#5]
I get this:

==> default: ---- Begin output of "bash"  "/tmp/chef-script20151208-2827-12oshqe" ----
==> default: STDOUT: 
==> default: STDERR: Exception in thread "main" java.lang.UnsupportedClassVersionError: org/glassfish/admin/cli/AsadminMain : Unsupported major.minor version 51.0
==> default: 	at java.lang.ClassLoader.defineClass1(Native Method)
==> default: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
==> default: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
==> default: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
==> default: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
==> default: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
==> default: 	at java.security.AccessController.doPrivileged(Native Method)
==> default: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
==> default: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
==> default: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
==> default: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
==> default: Could not find the main class: org.glassfish.admin.cli.AsadminMain. Program will exit.
==> default: ---- End output of "bash"  "/tmp/chef-script20151208-2827-12oshqe" ----
==> default: Ran "bash"  "/tmp/chef-script20151208-2827-12oshqe" returned 1
==> default: [2015-12-08T09:47:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by jimdowling** [comment]
Fixed, long time ago.
